# Generated by Django 5.2.5 on 2025-08-28 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='actaserviciotecnico',
            old_name='mantenimiento_atencionReclamo_Calidad',
            new_name='cambio_de_plan',
        ),
        migrations.RenameField(
            model_name='actaserviciotecnico',
            old_name='retiro_acometida',
            new_name='migracion',
        ),
        migrations.AddField(
            model_name='actaserviciotecnico',
            name='traslado_acometida',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='actaserviciotecnico',
            name='traslado_externo',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='actaserviciotecnico',
            name='traslado_interno',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='actaserviciotecnico',
            name='retiro',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='actaserviciotecnico',
            name='t_adicional',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
