# Generated by Django 5.2.5 on 2025-08-29 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0002_rename_mantenimiento_atencionreclamo_calidad_actaserviciotecnico_cambio_de_plan_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actaserviciotecnico',
            name='retiro',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='actaserviciotecnico',
            name='traslado_acometida',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='actaserviciotecnico',
            name='traslado_interno',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
