# Generated by Django 5.2.5 on 2025-09-02 03:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0003_alter_actaserviciotecnico_retiro_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='actaserviciotecnico',
            old_name='dni_cliente',
            new_name='dni_tecnico',
        ),
        migrations.RenameField(
            model_name='actaserviciotecnico',
            old_name='nombre_cliente',
            new_name='nombre_tecnico',
        ),
    ]
