# Generated by Django 5.2.5 on 2025-09-07 01:45

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0004_rename_dni_cliente_actaserviciotecnico_dni_tecnico_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cotizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_cotizacion', models.CharField(help_text="Identificador unico para generar las cotizaciones, formato a seguir: 'COT[numero][año]'", max_length=20, unique=True)),
                ('nombre_cotizacion', models.CharField(max_length=50)),
                ('ruc', models.CharField(max_length=30)),
                ('razon_social', models.CharField(max_length=30)),
                ('fecha_creacion', models.DateField(auto_now_add=True)),
                ('celular', models.CharField(max_length=9)),
                ('direccion', models.CharField(max_length=50)),
                ('correo', models.EmailField(max_length=254)),
                ('dato_ruc', models.CharField(max_length=30)),
                ('dato_empresa', models.CharField(max_length=50)),
                ('contacto_nombre', models.CharField(max_length=50)),
                ('contacto_correo', models.EmailField(max_length=254)),
                ('contacto_celular', models.CharField(max_length=9)),
                ('alcance_total_oferta', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Detalles_Cotizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField(help_text='Ingrese la descripción de la Cotización')),
                ('unidad', models.CharField(choices=[('', '-- Selecciona --'), ('UNIDAD', 'UNIDAD'), ('DECENA', 'DECENA')])),
                ('cantidad', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(300)])),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=12)),
                ('cotizacion_principal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='ventas.cotizacion')),
            ],
        ),
    ]
