# Generated by Django 5.2.5 on 2025-09-12 00:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0005_cotizacion_detalles_cotizacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('ruc', models.CharField(max_length=20, unique=True)),
                ('razon_social', models.CharField(max_length=20)),
                ('direccion', models.CharField(max_length=50)),
                ('distrito', models.CharField(max_length=20)),
                ('provincia', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('nombre', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='UnidadNegocio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('nombre', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='cotizacion',
            name='contacto_celular',
            field=models.CharField(blank=True, max_length=9, null=True),
        ),
        migrations.AlterField(
            model_name='cotizacion',
            name='contacto_correo',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='cotizacion',
            name='contacto_nombre',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='cotizacion',
            name='dato_empresa',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='cotizacion',
            name='dato_ruc',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cotizaciones', to='ventas.cliente'),
        ),
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apellidos', models.CharField(max_length=20, unique=True)),
                ('nombres', models.CharField(max_length=20, unique=True)),
                ('cargo', models.CharField(max_length=20, unique=True)),
                ('correo', models.EmailField(max_length=254)),
                ('Celular', models.CharField(max_length=9)),
                ('Sede', models.CharField(max_length=20, unique=True)),
                ('cliente_principal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacto', to='ventas.cliente')),
            ],
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='contacto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cotizaciones_contacto', to='ventas.contacto'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='proyecto_principal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proyecto', to='ventas.proyecto'),
        ),
    ]
