# Generated by Django 5.2.5 on 2025-09-12 00:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0007_populate_cotizacion_fks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cotizacion',
            name='alcance_total_oferta',
        ),
        migrations.RemoveField(
            model_name='cotizacion',
            name='contacto_celular',
        ),
        migrations.RemoveField(
            model_name='cotizacion',
            name='contacto_correo',
        ),
        migrations.RemoveField(
            model_name='cotizacion',
            name='contacto_nombre',
        ),
        migrations.RemoveField(
            model_name='cotizacion',
            name='dato_empresa',
        ),
        migrations.RemoveField(
            model_name='cotizacion',
            name='dato_ruc',
        ),
        migrations.AlterField(
            model_name='cotizacion',
            name='cliente',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='cotizaciones', to='ventas.cliente'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cotizacion',
            name='contacto',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='cotizaciones_contacto', to='ventas.contacto'),
            preserve_default=False,
        ),
    ]
