# Generated by Django 5.2.5 on 2025-09-12 00:59

import django.db.models.deletion
from django.db import migrations, models
from django.db import transaction


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0008_remove_cotizacion_alcance_total_oferta_and_more'),
    ]

    operations = [
        # Añadir el campo como NULLABLE primero para evitar violaciones de FK
        migrations.AddField(
            model_name='proyecto',
            name='unidad_negocio_principal',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='unidad_negocio', to='ventas.unidadnegocio'),
        ),

        # Crear una UnidadNegocio por defecto (si no existe) y asignarla a los proyectos que queden con NULL
        migrations.RunPython(
            code=lambda apps, schema_editor: (
                (lambda UnidadNegocio, Proyecto: (
                    (lambda unidad: Proyecto.objects.filter(unidad_negocio_principal__isnull=True).update(unidad_negocio_principal_id=unidad.pk))(
                        UnidadNegocio.objects.create(codigo='UN-1', nombre='Unidad por defecto') if not UnidadNegocio.objects.exists() else UnidadNegocio.objects.first()
                    )
                ))(apps.get_model('ventas', 'UnidadNegocio'), apps.get_model('ventas', 'Proyecto'))
            ),
            reverse_code=migrations.RunPython.noop,
        ),

        # Hacer la relación no-nullable ahora que todas las filas tienen valor
        migrations.AlterField(
            model_name='proyecto',
            name='unidad_negocio_principal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unidad_negocio', to='ventas.unidadnegocio'),
        ),
        migrations.AlterField(
            model_name='contacto',
            name='Sede',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='contacto',
            name='apellidos',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='contacto',
            name='cargo',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='contacto',
            name='nombres',
            field=models.CharField(max_length=20),
        ),
    ]
