# Generated by Django 5.2.5 on 2025-09-12 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0009_proyecto_unidad_negocio_principal_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unidadnegocio',
            name='nombre',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
