# Generated by Django 5.2.5 on 2025-09-17 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0010_alter_unidadnegocio_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='cotizacion',
            name='alcance_total_oferta',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
