# Generated by Django 5.2.5 on 2025-09-20 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0011_cotizacion_alcance_total_oferta'),
    ]

    operations = [
        migrations.AddField(
            model_name='cotizacion',
            name='estado_coti',
            field=models.CharField(choices=[('', '-'), ('En Negociación', 'En Negociación'), ('Ganado', 'Ganado'), ('Perdida', 'Perdida')], default='En Negociación', max_length=20),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='fecha_actualizacion_estado',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='forma_pago',
            field=models.CharField(blank=True, choices=[('', '-'), ('AL CONTADO', 'AL CONTADO'), ('30 DIAS', '30 DIAS'), ('60 DIAS', '60 DIAS')], max_length=20),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='incluye_igv',
            field=models.BooleanField(default=True, help_text='Si la cotización incluye IGV (18%)'),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='moneda',
            field=models.CharField(choices=[('', '-'), ('Soles', 'Soles'), ('Dolares', 'Dolares')], default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='tipo_cambio',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Tipo de cambio USD a PEN (se actualiza automáticamente desde BCR + 0.10)', max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='validez_oferta',
            field=models.CharField(choices=[('', '-'), ('15 dias', '15 dias'), ('21 dias', '21 dias'), ('30 dias', '30 dias'), ('45 dias', '45 dias'), ('60 dias', '60 dias')], default=1, max_length=20),
            preserve_default=False,
        ),
    ]
