# Generated by Django 5.2.5 on 2025-09-24 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0012_add_bcr_tipo_cambio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cotizacion',
            name='fecha_actualizacion_estado',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='cotizacion',
            name='forma_pago',
            field=models.CharField(blank=True, choices=[('', '-'), ('15 dias', '15 dias'), ('21 dias', '21 dias'), ('30 dias', '30 dias'), ('45 dias', '45 dias'), ('60 dias', '60 dias')], max_length=20),
        ),
    ]
