# Generated by Django 5.2.5 on 2025-09-24 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0013_alter_cotizacion_fecha_actualizacion_estado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalles_cotizacion',
            name='precio_unitario',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True),
        ),
    ]
