# Generated by Django 5.2.5 on 2025-09-27 20:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0014_alter_detalles_cotizacion_precio_unitario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='proyecto_principal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clientes', to='ventas.proyecto'),
        ),
    ]
