# Generated by Django 5.2.5 on 2025-10-07 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0015_alter_cliente_proyecto_principal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='razon_social',
            field=models.CharField(max_length=50),
        ),
    ]
