# Generated by Django 5.2.5 on 2025-10-07 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0016_alter_cliente_razon_social'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='ruc',
            field=models.CharField(max_length=20),
        ),
    ]
