# Generated by Django 5.2.5 on 2025-09-27 20:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ventas', '0015_alter_cliente_proyecto_principal'),
    ]

    operations = [
        migrations.CreateModel(
            name='Personal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(help_text='Indentificador único para el personal', max_length=20, unique=True)),
                ('nombres', models.CharField(help_text='Nombres para el personal', max_length=30)),
                ('apellidos', models.CharField(help_text='Apellidos para el personal', max_length=30)),
                ('cargo', models.CharField(help_text='Cargo que usara el usuario', max_length=30)),
                ('dni', models.CharField(help_text='Ingese N° DNI', max_length=8, unique=True)),
                ('empresa_afp', models.CharField(max_length=30)),
                ('numero_afp', models.CharField(max_length=20)),
                ('fecha_ingreso', models.DateField()),
                ('tipo_comision_afp', models.CharField(max_length=20)),
                ('bono', models.CharField(max_length=20)),
                ('activo', models.BooleanField(default=True)),
                ('modalidad', models.CharField(max_length=20)),
                ('domicilio', models.CharField(max_length=50)),
                ('inicio_de_contrato', models.DateField()),
                ('vencimiento_contrato', models.DateField()),
                ('num_emergencia', models.CharField(max_length=9)),
                ('correo', models.EmailField(max_length=254)),
                ('profesion', models.CharField(max_length=30)),
                ('id_proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personal_asignado', to='ventas.proyecto')),
            ],
        ),
        migrations.CreateModel(
            name='HijosPersonal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cumpleaños_hijo', models.DateField()),
                ('id_personal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personal', to='rrhh.personal')),
            ],
        ),
    ]
