# Generated by Django 5.2.5 on 2025-09-27 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rrhh', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hijospersonal',
            name='nombre_hijo',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='personal',
            name='contacto_emergencia',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
